export const EndPoints = {
  login: "/login",
  Countries: "/countries/?page=1",
  VerifyCode: "/verification/verify",
  Profile: "/profile",
  MarkAsOnline: "/profile/online",
  MarkAsOffline: "/profile/offline",
  UpdateProfileSettings: "/profile/settings",
  Statistics: "/profile/statistics",
  Specialities: "/select/specialities?page=1",
  Categories: "/select/categories?speciality_id=1",
  notificationSettings: "/notifications/settings",
  UploadMedia: "/uploader/media/upload",
  notifications: "/notifications",
  Consultants: "/consultants?filters",
  FollowingList: "/profile/followings",
  ToggleFavorite: "/users/:id/follow",
  Projects: "/projects?type=all",
  CreateProject: "/projects",
  CreateAttachment: "/projects/:id/attachments",
  ShowUser: "/users/:id",
  RejectProject: "/projects/:id/reject",
  AcceptProject: "/projects/:id/invitation/accept",
};
